### ISSUE TITLE
Direct link to a PDF is marked as a broken link

### ISSUE THREAD

**Issue by bensulli** [siteinspector/siteinspector#9] opened 2021-03-12 05:14 UTC
Scanning https://appliedmammal.com marks three PDF links as broken, but they appear to be just fine.

An example:
https://appliedmammal.com/content/brochures/Forest%20Herbicide%20Use.pdf

**Comment by omohokcoj** [comment] 2021-03-13 11:36
@bensulli this issue was caused by whitespaces in the URLs - it has been fixed in 1.0.4

**Closed by omohokcoj** 2021-03-13 11:36 UTC

**Comment by bensulli** [comment] 2021-03-13 18:59
Confirmed fixed :)
